#!/bin/bash
if [ "$UID" = 0 ]; then
  echo "Installing 'softwaves-manjaro' plymouth theme ..."
  mkdir -p /usr/share/plymouth/themes
  cp -r softwaves-manjaro /usr/share/plymouth/themes/
  echo "Applying 'softwaves-manjaro' plymouth theme ..."
  if which plymouth-set-default-theme &>/dev/null; then
    plymouth-set-default-theme -R softwaves-manjaro
  elif which update-alternatives update-initramfs &>/dev/null; then
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/softwaves-manjaro/softwaves-manjaro.plymouth 10
    update-alternatives --set default.plymouth /usr/share/plymouth/themes/softwaves-manjaro/softwaves-manjaro.plymouth
    update-initramfs -u
  else
    echo "Could not apply the theme automatically!"
    echo "Please! Apply it manually."
    exit 2
  fi
else
  if which sudo &> /dev/null; then
    sudo "$0"
  else
    echo "Please! Run this script as root."
    exit 1
  fi
fi
